version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/deploy/
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 1500
      runas: ubuntu
  BeforeInstall:
    - location: scripts/befor_install.sh
      timeout: 1500
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 1500
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 1500
      runas: ubuntu
